apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-server-app
  template:
    metadata:
      labels:
        app: todo-server-app
    spec:
      containers:
      - image: pavanvarikolu/wwabackend:v1.1.1
        name: container1
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: server-side-configs
        
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
  labels: 
      app: todo-server-app
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: todo-server-app
  type: LoadBalancer
  
  
